version: "3.4"
services:
  monolith_test:
    container_name: dendrite_monolith_test
    hostname: monolith
    entrypoint: ["bash", "./docker/test/monolith.sh"]
    build: ./
    volumes:
      - ..:/build
      - ./build/pkg:/build/pkg
      - ./build/bin:/build/bin
    networks:
      - internal
    depends_on:
      - postgres
    ports:
      - "8008:8008"
      - "8448:8448"

  postgres:
    container_name: dendrite_postgres
    hostname: postgres
    image: postgres:9.5
    restart: always
    volumes:
      - ./postgres/create_db.sh:/docker-entrypoint-initdb.d/20-create_db.sh
    environment:
      POSTGRES_PASSWORD: itsasecret
      POSTGRES_USER: dendrite
    networks:
      - internal
    ports:
      - 15432:5432

networks:
  internal:
    attachable: true
